# Generated by Django 4.1.6 on 2023-02-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mqtt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarningLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DeviceID", models.CharField(max_length=200)),
                ("WarningTime", models.DateTimeField()),
                ("WarningType", models.IntegerField()),
            ],
        ),
    ]
