# Generated by Django 4.1.6 on 2023-02-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mqtt", "0003_checkclient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkclient",
            name="client",
            field=models.CharField(
                blank=True, editable=False, max_length=200, null=True
            ),
        ),
    ]
